# SQL Project - Zomato Sales Analysis

-- 1. List the top 3 customers who have placed the highest number of orders.

select customer_id ,count(order_id) as Total_Customer_Orders 
from order_detail
group by customer_id
order by Total_Customer_Orders desc
limit 3
;

-- 2. Find the restaurant that has received the highest average rating.

select restaurant_name, round(avg(rrating),2) as avg_rrating 
from restaurant
group by restaurant_name 
order by avg_rrating desc
limit 1 
;

-- 3. List all orders from order_detail that were delivered in under 30 minutes.

select *, timestampdiff(minute, order_time, delivered_time) as delivered_time_minutes
from order_detail
where timestampdiff(minute, order_time, delivered_time) < 30
order by delivered_time_minutes desc;

-- 4. Calculate the total revenue generated by each food item. Display food_id, food_name
	  -- and Total revenue ordered by total revenue in descending order.

select f.food_id,
	   f.food_name,
	   sum(f.price_per_unit * orf.quantity) as total_revenue
from order_food orf
right join foods f on orf.food_id = f.food_id
group by f.food_name, f.food_id
order by total_revenue desc
;

-- 5. Find the second highest revenue-generating restaurant.

with revenue_cte as 
				(select rt.restaurant_id,
						rt.restaurant_name,
						sum(f.price_per_unit * orf.quantity) as total_revenue,
						dense_rank() over(order by sum(f.price_per_unit * orf.quantity)) as rank_by_revenue
				from order_food orf
				left join foods f on orf.food_id = f.food_id
				left join restaurant rt on orf.restaurant_id = rt.restaurant_id
				group by rt.restaurant_id, rt.restaurant_name
)
select *
from revenue_cte
where rank_by_revenue = 2
; 


-- 6. Find the 5 most popular food items based on the quantity sold.

select f.food_name , sum(orf.quantity) as total_sold_unit
from order_food orf
join foods f on orf.food_id = f.food_id
group by f.food_name
order by total_sold_unit desc
limit 5;

-- 7. List the top 3 Zomato employees with the highest average delivery ratings.

with ear_cte as (
				 select employee_id, 
				 	    employee_name, 
				 	    employee_avg_rating, 
				 	    dense_rank() over(order by employee_avg_rating desc) as highest_empl_ranking
				 from zomato_employee
				)
select *
from ear_cte
where highest_empl_ranking <=3                            
;

-- 8. Determine the month with the highest number of total orders placed.

select date_format(order_time, '%Y-%M') as order_month,
	   count(order_id) as total_orders
from order_detail
group by order_month
order by total_orders desc
limit 1
;

-- 9. Calculate the average order amount for each customer. Order by average order amount in descending order.

with oar_cte as (
				select orf.order_id,
					   orf.customer_id,
					   sum(orf.quantity * f.price_per_unit) as order_amount
				from order_food orf
				join foods f on orf.food_id = f.food_id
				group by orf.order_id, orf.customer_id
                )
select c.customer_id,
	   c.customer_name,
       round(avg(order_amount),2) as avg_order_amount
from oar_cte ot
join customer c on ot.customer_id = c.customer_id
group by c.customer_id, c.customer_name
order by avg_order_amount desc
;

-- 10. Identify the most frequent customer for each restaurant.

with customer_orders as (
							select od.restaurant_id,
								   od.customer_id,
                                   count(od.order_id) as orders_count
                            from order_detail od
                            group by od.restaurant_id, od.customer_id
						),
	 rank_customers as (
							select restaurant_id,
								   customer_id,
                                   orders_count,
                                   dense_rank() over(partition by restaurant_id order by orders_count desc) as cust_rank 
                            from customer_orders
                        )	
select r.restaurant_id, r.restaurant_name,
	   c.customer_id, c.customer_name,
       rc.orders_count
from rank_customers rc
join restaurant r on rc.restaurant_id = r.restaurant_id
join customer c on rc.customer_id = c.customer_id
where cust_rank = 1
;

-- 11. Calculate the total number of orders placed on weekends.

select count(order_id) as weekend_order
from order_detail
where dayofweek(order_time) In (1, 7)
;

-- 12. Calculate the average delivery time (in minutes) for orders placed on weekdays versus weekends.

SELECT 
    CASE 
        WHEN DAYOFWEEK(order_time) IN (1, 7) THEN 'Weekend'
        ELSE 'Weekday'
    END AS day_type,
    ROUND(
        AVG(TIMESTAMPDIFF(MINUTE, order_time, delivered_time)), 
        2
    ) AS avg_delivery_time_minutes
FROM order_detail
GROUP BY day_type;

-- 13. List the top 5 most expensive food items. Display food_id, food_name, and
		 -- price_per_unit for all food items with the highest 5 prices.

with rank_food as 
(
SELECT 
    food_id,
    food_name,
    price_per_unit,
    dense_rank() over(ORDER BY price_per_unit DESC) as price_rank
FROM foods
)
select food_id,
       food_name,
	   price_per_unit
from rank_food
where price_rank <= 5
order by price_per_unit desc
;

-- 14. Find the restaurant with the most diverse menu (i.e., the highest number of food items).

SELECT 
    r.restaurant_id,
    r.restaurant_name,
    COUNT(DISTINCT ofd.food_id) AS total_food_items
FROM order_food ofd
JOIN restaurant r 
    ON ofd.restaurant_id = r.restaurant_id
GROUP BY r.restaurant_id, r.restaurant_name
ORDER BY total_food_items DESC
LIMIT 1;

-- 15. Calculate total payment amount for each payment type.

SELECT 
       pt.payment_type,
       SUM(f.price_per_unit * orf.quantity) AS total_payment_amount
FROM payment_table pt
join order_detail od on pt.order_id = od.order_id
join order_food orf on od.order_id = orf.order_id
join foods f on orf.food_id = f.food_id
where pt.payment_status = "paid"
GROUP BY pt.payment_type
ORDER BY total_payment_amount DESC
;

